version: 2

sources:
  - name: raw
    database: cafe_location_intelligence
    schema: raw
    tables:
      - name: raw_google_places_cafes
      - name: raw_google_nearby_places
      - name: manual_cafe_enrichment